# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: app_database
  host: db
  user: postgres
  password:
    
local: &local
  adapter: sqlite3
  pool: 5 
  timeout: 5000
  database: db/development.sqlite3

development:
  <<: *default

test:
  <<: *local

production:
  <<: *default
  
